### ISSUE TITLE
Update to Plasma 5.21 

### ISSUE THREAD

**Issue by mateushonorato** [psifidotos/plasma-systray-latte-tweaks#10]
I've updated to plasma 5.21 and now it seems like I can't click on some icons from electron apps to open them while this is installed. Removing the extension seems to have fixed the problem. Would it be possible to update the basis of this extension to 5.21 to see if it gets fixed?

**Comment by psifidotos** [comment]
published, https://github.com/psifidotos/plasma-systray-latte-tweaks/releases/tag/v5.21.0
