### ISSUE TITLE
Some idea about the background layer

### ISSUE THREAD

**Issue by trmdi** [psifidotos/plasma-systray-latte-tweaks#11]
1, Can the background's RGBA and radius be adjustable?
3, Can the background be shown without having to reverse the color of icons (and make it monochrome)?

Something like this:

![image](https://user-images.githubusercontent.com/11857205/110339339-a5ae2f00-805a-11eb-9e83-c2dd8365e2b4.png)

Otherwise it looks too bold in some themes;

![image](https://user-images.githubusercontent.com/11857205/110340863-4f41f000-805c-11eb-98fd-9d40a404c7d3.png)

**Comment by trmdi** [comment]
Also, the arrow icon of the Deepin theme becomes this:
![image](https://user-images.githubusercontent.com/11857205/110341505-faeb4000-805c-11eb-8887-1ba844b2df8f.png)
(when the "reversed color" feature is not enabled)

**Comment by psifidotos** [comment]
Having user specified background color I don't like it because that would open plenty of user requests afterwards.

For the radius we can have an option
For the solidness we can have an opacity slider, and based on its value contents could be drawn accordingly to provide the results you have screenshoted. For example background opacity below 40% could result to items painted with text Color like your second screenshot

**Comment by psifidotos** [comment]
> Also, the arrow icon of the Deepin theme becomes this:
> ![image](https://user-images.githubusercontent.com/11857205/110341505-faeb4000-805c-11eb-8887-1ba844b2df8f.png)
> (when the "reversed color" feature is not enabled)

It could be the specific icon having too much transparency

**Comment by trmdi** [comment]
> > Also, the arrow icon of the Deepin theme becomes this:
> > ![image](https://user-images.githubusercontent.com/11857205/110341505-faeb4000-805c-11eb-8887-1ba844b2df8f.png)
> > (when the "reversed color" feature is not enabled)
> 
> It could be the specific icon having too much transparency

But it does not happen with Plasma's systray, so there must be something wrong with Latte's one.

**Comment by psifidotos** [comment]
you can play with that at: https://github.com/psifidotos/plasma-systray-latte-tweaks/blob/master/org.kde.plasma.private.systemtray/contents/ui/ExpanderArrow.qml

**Comment by trmdi** [comment]
> you can play with that at: https://github.com/psifidotos/plasma-systray-latte-tweaks/blob/master/org.kde.plasma.private.systemtray/contents/ui/ExpanderArrow.qml

Because the loader is still active in my case.
https://github.com/psifidotos/plasma-systray-latte-tweaks/blob/43c55a0d8676ba15c1488f1735133ce79473179d/org.kde.plasma.private.systemtray/contents/ui/ExpanderArrow.qml#L123

It should be inactive in this case.
