### ISSUE TITLE
some tray icons won't follow system colors anymore

### ISSUE THREAD

**Issue by begonia208** [psifidotos/plasma-systray-latte-tweaks#14]
I'm using the plasma-systray-latte-tweaks. And it seems that some tray-icons follow color scheme (e.g. Klipper, Nextcloud) but others don't (sound volume, wireless).
On my laptop I still use plasma 5.22 and on my desktop 5.23. That makes no difference. I was searching in all directions what could cause this but I really can't find anything. 
Could it be that the plasma-system-latte-tweaks need to be updated to the newer plasma versions?
Thank you

**Comment by psifidotos** [comment]
fixed, you need to use new version for Plasma 5.23 https://github.com/psifidotos/plasma-systray-latte-tweaks/releases/tag/v5.23.0
