### ISSUE TITLE
Plasma 5.24 - the new kwalltet icon is not properly colored

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/plasma-systray-latte-tweaks#16]
After the update to Plasma 5.24 a new item in systray showed up: " wallet management". I believe this is kwallet element that was changed in this version. I read about it but don't remember the exact nature of the changes but now kwallet is opened by default after auto-login (not sure how it was before). Anyway, this new element is not following the theme or coloring that is used by systray tweak.

See the icon in the upper, right corner. If it wasn't highlated by the cursor, it would be completely invisible.

![Screenshot_20220209_212150](https://user-images.githubusercontent.com/10132958/153284381-d53addd3-559a-42ad-b31e-6cf82e6ea931.jpeg)

So as usual, systray tweak needs some update to be compatible.

EDIT: Bluetooth icon is grayed out because Bluetoth is inactive at the moment. Still, coloring is correct and icon is visible. Kwallet's one is invisible against a dark, blurry background.

**Comment by psifidotos** [comment]
this is a plasma bug, latte systray tweaks does not autocolor items in the popup

**Comment by michaldybczak** [comment]
Thanks. I created a bug on KDE bugtracker:

https://bugs.kde.org/show_bug.cgi?id=449941

Will see what comes from it.
