### ISSUE TITLE
Empty entries in settings

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/plasma-systray-latte-tweaks#2]
Some update in plasma or kf5 may have broken sth, please see screenshot:

![image](https://user-images.githubusercontent.com/3875196/82330200-843b6400-99b0-11ea-96b4-2c3f06263805.png)

This doesn't happen with plasma's version

**Comment by psifidotos** [comment]
What is your plasma version?

**Comment by kupiqu** [comment]
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2

**Comment by psifidotos** [comment]
with latte-dock -d what error do you see?

**Comment by psifidotos** [comment]
and of course, do you have update to 5.18 version? from, https://github.com/psifidotos/plasma-systray-latte-tweaks/releases ?

**Comment by kupiqu** [comment]
I use master version, should it work fine, right? Or is there something about Plasma 5.19 that may break it?

I will try to collect debug info and post it here

**Comment by psifidotos** [comment]
I havent made any commits for plasma 5.19

**Comment by kupiqu** [comment]
These are the only two errors I've seen related to the systray. I open the system settings only once and the first one appeared several times throughout the latte debug info, whereas the second just appeared once:

```
"file:///PATH/plasma-systray-latte-tweaks/org.kde.plasma.systemtray/contents/ui/main.qml:81: TypeError: Cannot read property 'children' of null"
```

```
"file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:299:25: QML StackView: replace: file:///PATH/plasma-systray-latte-tweaks/org.kde.plasma.private.systemtray/contents/ui/ConfigEntries.qml:190 Cannot override FINAL property"
```

[ PATH is my path at $HOME where I have the repo and I have symbolic links to the right places ]

**Comment by hoangnm205** [comment]
This error happen only when using latte dock :((

**Comment by kupiqu** [comment]
> This error happen only when using latte dock :((

I don't know how or why, but it came back to normal in my system. Maybe some recent commit or a reboot. Will say if this issue comes back

**Comment by NovaViper** [comment]
I'm having the same issue here, im using the latest Latte dock version (0.9.85) from the Rik Mills PPA. I have the same version of KDE as the @kupiqu

**Comment by NovaViper** [comment]
When I do 'latte-dock -d' and open up the system tray settings, I get lots of errors like this: https://gist.github.com/NovaViper/48a5e5d8a4eecc8ab0e59792d2f71dcd

**Comment by trancong12102** [comment]
I'm having same issue after upgrade plasma to 5.18.5 
OS: Manjaro KDE 20.0.1
Plasma: 5.18.5
KDE framework: 5.70.0
Qt: 5.14.2

**Comment by trancong12102** [comment]
tweaks branch work fine 
But 5.18.0 release don't work :((

**Comment by trmdi** [comment]
After comparing `ConfigEntries.qml` with upstream, I see that changing `currentValue` to `myCurrentValue` probably solves this.
