### ISSUE TITLE
 plasma-systray-latte-tweaks and plasma 5.19...

### ISSUE THREAD

**Issue by begonia208** [psifidotos/plasma-systray-latte-tweaks#4]
I am trying plasma 5.19 on my Neon laptop (plasma 5.18.90). I notice that the 
plasma-systray-latte-tweaks won't function as they should under this latest plasma release. Thank you!

**Comment by psifidotos** [comment]
It will need a 5.19 version. This is scheduled when 5.19 reaches Tumbleweed.

**Comment by psifidotos** [comment]
fixed https://github.com/psifidotos/plasma-systray-latte-tweaks/releases
