### ISSUE TITLE
Installing | Error Loading QML Files

### ISSUE THREAD

**Issue by GalGreenfield** [psifidotos/plasma-systray-latte-tweaks#7]
I followed the installation process and copied the directories as required, and after doing so, where there should be the widget with my background processes and notifications there's this error now:

> Error loading QML file: file:///home/galgreenfield/.local/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:273:19: Type ExpandedRepresentation unavailable
file:///home/galgreenfield/.local/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ExpandedRepresentation.qml:40:5: PlasmaExtras.PlasmoidHeading is not a type

What's causing this and how can I solve it?

**Comment by pkfm** [comment]
Forgive me for stating the obvious, but check that your versions match. I received the same error and it was due to a version mismatch.

```
plasmashell --version
```

**Comment by psifidotos** [comment]
you should use the version that is relevant to your plasma version
