### ISSUE TITLE
Need update to Plasma 5.20 systray goodies

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/plasma-systray-latte-tweaks#8]
There are no immediate breakages with Plasma 5.20, all seems to work just fine, but we are not seeing grid placed notifications and other improvements.

If you find some time to upgrade this small gem, we would be very happy users :).

Thank you :)

**Comment by fitrh** [comment]
Yeah, same here.
![Screenshot_20201021_194015](https://user-images.githubusercontent.com/55179750/96715566-5f6f7080-13d6-11eb-88cf-531859c7c057.jpeg)

**Comment by alextorma** [comment]
Agreed. I don't know much too much about writing new qml but I'm not bad at editing already written text and I'd be willing to lend a hand if given some direction!

**Comment by psifidotos** [comment]
just released... if you find any issues feel free to provide PullRequests

**Comment by michaldybczak** [comment]
Thanks! Seems to work as expected :D
Although, this pin icon, does it suppose to be so big?

![Screenshot_20201024_223535](https://user-images.githubusercontent.com/10132958/97093104-a44f0d80-1649-11eb-8cb8-9ba10103cb5b.jpeg)

On a presentation, this looks quite smaller:

![Screenshot_20201024_223919](https://user-images.githubusercontent.com/10132958/97093139-cc3e7100-1649-11eb-82a5-52cfa6e2226b.jpeg)

But that's probably desktop theme dependent and probably is more touch friendly. It's not a bad thing, just looks out of place or I didn't get use to seeing the pin icon few times bigger than usual.

**Comment by alextorma** [comment]
Thanks for the speedy update.

Had a question for you - on previous versions this would (at least seem to) recolor icons that were "problematic" even if the colors>theme in Latte wasn't set to "Smart" (meaning that if it was a dark icon on a dark panel/background or a light icon on a light panel/background, the icon would be recolored, but wouldn't switch if/when the background color changed as if it had been "Smart" colored. Is this a functionality that can be restored? I didn't realize that this tweak was doing it until recently (I never used "Smart" theme). It's particularly noticeable for me with the caffeine-ng systray applet.

**Comment by psifidotos** [comment]
you mean to autocolor at all cases?

**Comment by michaldybczak** [comment]
@torma616, autocolor option available in latte-tweaks is influencing icons' color. If it's on, it's monochromatic coloring it depending on the desktop theme which decides the panel's background. While Smart option is coloring panel/dock background and then indirectly influencing autocolor function. At least this is how I understand it. 
It's behaving like it should, so check the auto color box with the problematic icon.

**Comment by psifidotos** [comment]
> @torma616, autocolor option available in latte-tweaks is influencing icons' color. If it's on, it's monochromatic coloring it depending on the desktop theme which decides the panel's background. While Smart option is coloring panel/dock background and then indirectly influencing autocolor function. At least this is how I understand it.
> It's behaving like it should, so check the auto color box with the problematic icon.

Not exactly, the intended behavior is the following:
1. If the user has chosen in Latte Appearance, Plasma Theme then the systray applets are never colored. (this is fixed in upcoming release)
2. If the user has chosen in Latte Appearance, Reverse Theme then the systray applets respect the AutoColor option
3. If the user has chosen in Latte Appearance, Smart Theme then the systray applets respect the AutoColor option

**Comment by michaldybczak** [comment]
Ah, so Plasma appearance is the exception here (coloring is ignored).
OK, so when you change this in the next release, this will be behaving like I mentioned:

Plasma, Reverse, Smart - are influencing background (which is theme dependent)
Auto Color - is influencing icon's coloring, depending on the background.

This seems (at least from my perspective) the best and most logical choice and give the most flexible options, so I'm happy about this upcoming change.

Since the static panel's icon's colors are often an issue, the auto-color should be part of the Plasma's systray anyway. Your latte-tweaks fixes it, but those who are unaware of it (many, many users), they have to work around this using certain packages (like proper dropbox's icon) and certain themes. Often, there is no perfect choice.

Do I get this right, that latte-tweaks-systray will work on Plasma's default panel as well?
If the auto-coloring will be left as an independent option (regardless of the panel's background), it will be finally in place where this could become part of the official systray (fixing many potential color issues). What do you think @psifidotos?

From what I see, auto-coloring is working awesome, if we have the ability to turn it off in certain cases. I would imagine, that if it became a part of default systray, we would have to leave auto-color off as default and then inform user's that if certain color's doesn't work on a panel, they could be monochromatically auto-colored by ticking the option on.

**Comment by alextorma** [comment]
> 1. If the user has chosen in Latte Appearance, Plasma Theme then the systray applets are never colored. (this is fixed in upcoming release)

I see. That's unfortunate in my case, I came to really enjoy the appearance of the "Plasma" theme with the autocolored/monochromatic icons (basically, a  reverse "Reverse" theme). I


s there any way to possibly enable this via a config? Even if you could point me in the right direction of which qml files to hack on to bring this back for my own personal copy, I'd really appreciate it!
